export const TekkenStages = [
    'Artic Snowfall',
    'Devils Pit',
    'Cave of Enlightenment',
    'Abandoned Temple',
    'Arena',
    'Brimstone & Fire',
    'Forgotten Realm',
    'G Corp. Helipad',
    'G Corp. Helipad (Night)',
    'Geometric Plane',
    'Dragons Nest',
    'Hammerhead',
    'Howard Estate',
    'Infinite Azure',
    'Infinite Azure 2',
    'Jungle Outpost',
    'Jungle Outpost 2',
    'Kinder Gym',
    'Last Day on Earth',
    'Mishima Dojo',
    'Mishima Building',
    'Howard Estate',
    'Precipe of Fate',
    'Duomo di Sirio',
    'Violet Systems',
    'Vermillion Gates'
]

export const TekkenCharacters = [
    'Akuma',
    'Alisa',
    'Anna',
    'Armor King',
    'Asuka',
    'Bob',
    'Bryan',
    'Claudio',
    'Devil Jin',
    'Dragunov',
    'Eddy',
    'Eliza',
    'Fahkumram',
    'Feng',
    'Ganryu',
    'Geese',
    'Gigas',
    'Heihachi',
    'Hwoarang',
    'Jack-7',
    'Jin',
    'Josie',
    'Julia',
    'Katarina',
    'Kazumi',
    'Kazuya',
    'King',
    'Kuma',
    'Kunimitsu',
    'Lars',
    'Law',
    'Lee',
    'Lei',
    'Leo',
    'Leroy',
    'Lili',
    'Lucky Chloe',
    'Marduk',
    'Master Raven',
    'Miguel',
    'Negan',
    'Nina',
    'Noctis',
    'Panda',
    'Paul',
    'Shaheen',
    'Steve',
    'Xiaoyu',
    'Yoshimitsu',
    'Zafina'
]

